name: Build
on:
  push:
    branches:
      - 'main'

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  chrome:
    name: e2e chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn global add nx --silent && echo "SECRET=abc" > .env

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v5
        with:
          command: yarn e2e:ci-chrome

  firefox:
    name: e2e firefox
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn global add nx --silent && echo "SECRET=abc" > .env

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v5
        with:
          command: yarn e2e:ci-firefox

  bump-version:
    needs: [chrome, firefox]
    name: bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          major-wording: 'BREAKING CHANGE,major'
          minor-wording: 'feat'
          patch-wording: 'patch,fix,fixes,chore,ci,style'
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    if: ${{ !github.event.act }}
    needs: [bump-version]
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build majesdash
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/majesdash:develop
            ghcr.io/majesnix/majesdash:develop

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'New version of {{ EVENT_PAYLOAD.repository.full_name }} has been published.'
