name: Test and Bump
on:
  push:
    branches:
      - 'main'

jobs:
  chrome:
    name: e2e chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn global add nx --silent && echo "SECRET=abc" > .env

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          command: yarn e2e:ci-chrome

  firefox:
    name: e2e firefox
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn global add nx --silent && echo "SECRET=abc" > .env

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          command: yarn e2e:ci-firefox

  bump-version:
    needs: [chrome, firefox]
    name: bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          major-wording: 'BREAKING CHANGE,major'
          minor-wording: 'feat'
          patch-wording: 'patch,fix,fixes,chore,ci'
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
